pools:
  - provider: "colab_endpoint"
    pool_name: "colab_pool"
    strategy: "round_robin"
    cooldown_after_fail_s: 30
    keys:
      - key_id: "colab_key_1"
        env_var_name: "COLAB_API_KEY_1"
        headers:
          Authorization: "Bearer ${COLAB_API_KEY_1}"
      - key_id: "colab_key_2"
        env_var_name: "COLAB_API_KEY_2"
        headers:
          Authorization: "Bearer ${COLAB_API_KEY_2}"
  - provider: "kaggle_endpoint"
    pool_name: "kaggle_pool"
    strategy: "random"
    cooldown_after_fail_s: 20
    keys:
      - key_id: "kaggle_key_1"
        env_var_name: "KAGGLE_API_KEY_1"
        headers:
          Authorization: "Bearer ${KAGGLE_API_KEY_1}"
  - provider: "self_hosted_gpu"
    pool_name: "self_hosted_pool"
    strategy: "least_recent"
    cooldown_after_fail_s: 10
    keys:
      - key_id: "self_hosted_key_1"
        env_var_name: "SELF_HOSTED_API_KEY"
        headers:
          X-API-Key: "${SELF_HOSTED_API_KEY}"
